name: 04-01-runners
on: workflow_dispatch # event tirgger
jobs: 
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"  
  my-fourth-job:
    runs-on: self-hosted
    steps:
      - run: echo "Hello World"
